import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import StoreProvider from '@/store/StoreProvider';
import { QuestionnaireObserver } from './QuestionnaireObserver';
import './globals.css';

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Obrio Test',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <QuestionnaireObserver />

      <html lang='en'>
        <body className={`${openSans.className} main`}>{children}</body>
      </html>
    </StoreProvider>
  );
}
